# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import SensorService_pb2 as SensorService__pb2


class SensorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConsultarListaPorLocalizacao = channel.unary_unary(
                '/sensor_service.SensorService/ConsultarListaPorLocalizacao',
                request_serializer=SensorService__pb2.Localizacao.SerializeToString,
                response_deserializer=SensorService__pb2.ListaDados.FromString,
                )
        self.ConsultarListaPorData = channel.unary_unary(
                '/sensor_service.SensorService/ConsultarListaPorData',
                request_serializer=SensorService__pb2.Data.SerializeToString,
                response_deserializer=SensorService__pb2.ListaDados.FromString,
                )
        self.ConsultarListaPorDataELocalizacao = channel.unary_unary(
                '/sensor_service.SensorService/ConsultarListaPorDataELocalizacao',
                request_serializer=SensorService__pb2.LocalData.SerializeToString,
                response_deserializer=SensorService__pb2.ListaDados.FromString,
                )


class SensorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConsultarListaPorLocalizacao(self, request, context):
        """Consultar dados por localização
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarListaPorData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarListaPorDataELocalizacao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConsultarListaPorLocalizacao': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarListaPorLocalizacao,
                    request_deserializer=SensorService__pb2.Localizacao.FromString,
                    response_serializer=SensorService__pb2.ListaDados.SerializeToString,
            ),
            'ConsultarListaPorData': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarListaPorData,
                    request_deserializer=SensorService__pb2.Data.FromString,
                    response_serializer=SensorService__pb2.ListaDados.SerializeToString,
            ),
            'ConsultarListaPorDataELocalizacao': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarListaPorDataELocalizacao,
                    request_deserializer=SensorService__pb2.LocalData.FromString,
                    response_serializer=SensorService__pb2.ListaDados.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sensor_service.SensorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SensorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConsultarListaPorLocalizacao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sensor_service.SensorService/ConsultarListaPorLocalizacao',
            SensorService__pb2.Localizacao.SerializeToString,
            SensorService__pb2.ListaDados.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConsultarListaPorData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sensor_service.SensorService/ConsultarListaPorData',
            SensorService__pb2.Data.SerializeToString,
            SensorService__pb2.ListaDados.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConsultarListaPorDataELocalizacao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sensor_service.SensorService/ConsultarListaPorDataELocalizacao',
            SensorService__pb2.LocalData.SerializeToString,
            SensorService__pb2.ListaDados.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
