# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SensorService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13SensorService.proto\x12\x0esensor_service\"\x14\n\x04\x44\x61ta\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\"\n\x0bLocalizacao\x12\x13\n\x0blocalizacao\x18\x01 \x01(\t\"[\n\tLocalData\x12*\n\x05local\x18\x01 \x01(\x0b\x32\x1b.sensor_service.Localizacao\x12\"\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x14.sensor_service.Data\"D\n\x04\x44\x61\x64o\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x13\n\x0blocalizacao\x18\x03 \x01(\t\x12\r\n\x05valor\x18\x04 \x01(\x02\"1\n\nListaDados\x12#\n\x05\x64\x61\x64os\x18\x01 \x03(\x0b\x32\x14.sensor_service.Dado\"\x0e\n\x0c\x45mptyMessage2\x95\x02\n\rSensorService\x12Y\n\x1c\x43onsultarListaPorLocalizacao\x12\x1b.sensor_service.Localizacao\x1a\x1a.sensor_service.ListaDados\"\x00\x12K\n\x15\x43onsultarListaPorData\x12\x14.sensor_service.Data\x1a\x1a.sensor_service.ListaDados\"\x00\x12\\\n!ConsultarListaPorDataELocalizacao\x12\x19.sensor_service.LocalData\x1a\x1a.sensor_service.ListaDados\"\x00\x42\x37\n\x1bio.grpc.examples.iotserviceB\x0fIoTServiceProtoP\x01\xa2\x02\x04TEMPb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SensorService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.iotserviceB\017IoTServiceProtoP\001\242\002\004TEMP'
  _DATA._serialized_start=39
  _DATA._serialized_end=59
  _LOCALIZACAO._serialized_start=61
  _LOCALIZACAO._serialized_end=95
  _LOCALDATA._serialized_start=97
  _LOCALDATA._serialized_end=188
  _DADO._serialized_start=190
  _DADO._serialized_end=258
  _LISTADADOS._serialized_start=260
  _LISTADADOS._serialized_end=309
  _EMPTYMESSAGE._serialized_start=311
  _EMPTYMESSAGE._serialized_end=325
  _SENSORSERVICE._serialized_start=328
  _SENSORSERVICE._serialized_end=605
# @@protoc_insertion_point(module_scope)
